version: '3.4'

services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=de002
            - MYSQL_ROOT_PASSWORD=pass
        ports:
            - "127.0.0.1:3306:3306"

    app:
        build: .
        depends_on:
          - db
        ports:
          - "127.0.0.1:3000:3000"
        volumes:
          - ./src:/app
